config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  
  # Configuracion rutas users -> Solo se permite new y create 
  resources :users, only: [:new, :create]
  
  # Configuracion rutas articles 
  resources :articles do
    resources :comments, only: [:create]
  end
  
  # Configuracion rutas login new, create y logout
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string(150)
#  body       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  
  validates :title, presence: true, length: {maximum: 100}
  validates :body, presence: true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  article_id :integer
#

class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
  
  validates :body, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(100)
#  password_digest :string
#  name            :string(100)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
    has_secure_password validations: false    
    
    has_many :articles
    has_many :comments
    
    validates :email, uniqueness: true, format: /@/
	validates :password, presence: true, on: :create
	validates :password, length: { in: 6..20 }, allow_nil: true
	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # Metodo para autenticar al usuario
  def sign_in(user)
    cookies.permanent.signed[:user_id] = user.id
    @current_user = user
  end
  
  # Metodo para cerrar sesion del usuario
  def sign_out
    cookies.delete(:user_id)
    @current_user = nil
  end
  
  private
  
    # Metodo que valida si el usuario esta autenticado
    def signed_in?
      !current_user.nil?
    end
    helper_method :signed_in?
    
    # Metodo que devuelve el usuario que esta autenticado
    def current_user
      @current_user ||= User.find(cookies.signed[:user_id]) if cookies.signed[:user_id]
    rescue ActiveRecord::RecordNotFound
    end
    helper_method :current_user
    
    # Metodo que valida si el Usuario ya esta autenticado lo redirija a la ruta de root_path
		def public_access
			redirect_to root_path if signed_in?
		end
		
	  # Metodo que valida si el usuario no esta logeado lo redirija a la pagina de logeo
		def private_access
			redirect_to :login unless signed_in?
		end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    # Valida que metodos estan restringidos para usuarios no logeados
    before_action :private_access, except: [:index, :show]

    
    def index
        @articles = Article.all.order("created_at DESC")
    end
    
    def new
        @article = Article.new
    end
    
    def create
        @article = Article.new(article_parameter)
        @article.user = current_user
        if @article.save
            redirect_to articles_path, notice: "El post ha sido creado con éxito"
        else
            render :new
        end
    end
    
    def show
        @article = Article.find(params[:id]);
        # Este variable de instancia se crea para validar el modelo de comentarios a la hora de crearlos
        @comment = Comment.new
    end
    
    def edit
        @article = Article.find(params[:id]);
    end
    
    def update
        @article = Article.find(params[:id]);
        if @article.update(article_parameter)
            redirect_to articles_path, notice: "El post ha sido actualizado con éxito"
        else
            render :edit
        end
    end
    
    def destroy
        article = Article.find(params[:id])
        article.destroy
        redirect_to articles_path
    end
    
    private

      	def article_parameter
      		params.require(:article).permit(:title, :body)
      	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        article = Article.find(params[:article_id]);
        @comment = article.comments.new(comments_params)
        
        if @comment.save
            @article = article
            redirect_to article_path(@article)
        else
            @article = Article.find(params[:article_id]);
            render "articles/show"
        end
    end
    
    private
    
        def comments_params
            params.require(:comment).permit(:body).merge(user: current_user)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    # Se ejecuta el merodo public_access para todas las acciones excepto destroy
    before_action :public_access, except: [:destroy]
    
    def new
        
    end
    
    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            sign_in(user)
            redirect_to root_path
        else
            redirect_to login_path, notice: "Tu email y/o contraseña son inválidas. Intenta nuevamente."
        end
    end
    
    def destroy
        sign_out
        redirect_to root_path
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    def create
      
      @user = User.new(user_params)
      
      if @user.save
        user = User.find_by(email: @user.email)
        if user && user.authenticate(@user.password)
          sign_in(user)
          redirect_to root_path
        else
          render :new
        end
      else
        render :new
      end
    end
    
    private
    
      def user_params
        params.require(:user).permit(:email, :password, :name)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
        options = {
          filter_html:     true,
          hard_wrap:       true, 
          link_attributes: { rel: 'nofollow', target: "_blank" },
          space_after_headers: true, 
          fenced_code_blocks: true
        }
    
        extensions = {
          autolink:           true,
          superscript:        true,
          disable_indented_code_blocks: true
        }
    
        renderer = Redcarpet::Render::HTML.new(options)
        markdown = Redcarpet::Markdown.new(renderer, extensions)
    
        markdown.render(text).html_safe
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def form_title
        @article.new_record? ? "Agregar Post" : "Modificar Post"
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
		    <h1><%= form_title %></h1>
		    
		    <% if @article.errors.any? %>			 
				<div class="alert alert-danger">
					<ul>
				    	<% @article.errors.full_messages.each do |msg| %>
				      		<li><%= msg %></li>
				    	<% end %>
				    </ul>
				</div>
			<% end %>
			
			<%= form_for @article do |f|%>
		    
		        <div class="form-group">
					<%= f.text_field :title, class: "form-control input-lg", placeholder: "Ingresa un Titulo" %>
				</div>
		    
		        <div class="form-group">
                    <%= f.text_area :body, class: "form-control", rows: "10", placeholder: "Ingresa el cuerpo del post" %>
                </div>

                <div class="actions text-right">
                    <%= f.submit form_title, class: "btn btn-primary btn-lg btn-block" %>
                </div>
		    
		    <% end %>
			
		</div>
	</div>
</div>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            
            <% if flash[:notice] %>
            	<div class="alert alert-info text-center" role="alert"><%= flash[:notice] %></div>
            <% end %>
            
            <% @articles.each do |article| %>
                <div class="article">
                    <div class="article-title">
                        <span class="title"><%= link_to article.title, article %></span>
                        <span class="description">Publicado por <%= article.user.email %> <%= time_ago_in_words article.created_at %></span>
                    </div>
                    <div class="article-body">
                        <% if article.body.length > 250 %>
                            <%= markdown(article.body[0..250] + "...") %>
                        <% else %>
                            <%= markdown(article.body) %>
                        <% end %>
                    </div>
                    <% if signed_in? %>
                        <% if current_user.id == article.user.id %>
                            <div class="article-tools">
                                <%= link_to "<span class='glyphicon glyphicon-pencil'></span> Editar".html_safe, edit_article_path(article) %>
                                <%= link_to "<span class='glyphicon glyphicon-trash'></span> Eliminar".html_safe, article, method: :delete, data: { confirm: "¿Estás seguro de eliminar este post?" } %>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            <div class="article">
                <div class="article-title">
                    <span class="title"><%= @article.title %></span>
                </div>
                <div class="article-body">
                    <%= markdown(@article.body) %>
                </div>
                <% @article.comments.each do |comment| %>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <%= comment.user.email %> realizo el comentario <%= time_ago_in_words comment.created_at %>
                        </div>
                        <div class="panel-body">
                            <%= markdown(comment.body) %>
                        </div>
                    </div>
                <% end %>
                
                <% if signed_in? %>
                    <% if @comment.errors.any? %>
                  	    <br />
                        <div class="alert alert-danger">
                            <ul>
                      	        <% @comment.errors.full_messages.each do |msg| %>
                      		        <li><%= msg %></li>
                      		    <% end %>
                      	    </ul>
                        </div>
                    <% end %>
                
                    <%= form_for [@article, @article.comments.build] do |f| %>
                        <div class="form-group">
                            <%= f.text_area :body, class: "form-control", placeholder: "Agregar Comentario" %>
                        </div>
            
                        <div class="actions text-right">
                            <%= f.submit "Comentar", class: "btn btn-primary" %>
                        </div>
                    <% end %>
                <% end %>
                
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">SuperBlog</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "SuperBlog", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if signed_in? %>
              <li><%= link_to "Nuevo Post", new_article_path %></li>
              <li><%= link_to "Salir", logout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Regístrate", new_user_path %></li>
              <li><%= link_to "Login", login_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </div>
  </div><!-- /.container -->
</nav>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Crear Cuenta</h1>
      
      <% if @user.errors.any? %>      
        <div class="alert alert-danger">
          <ul>
              <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
      <% end %>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.email_field :email, class: "form-control input-lg", placeholder: "Email" %>
        </div>

        <div class="form-group">
          <%= f.password_field :password, class: "form-control input-lg", placeholder: "Contraseña" %>
        </div>

        <div class="form-group">
          <%= f.text_field :name, class: "form-control input-lg", placeholder: "Nombre" %>
        </div>

        <div class="actions">
          <%= f.submit "Crear Usuario", class: "btn btn-primary btn-block btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>